### PR TITLE
KYLIN-3475 Make calcite connection is more configurable

### PR DESCRIPTION
**Pull request by ian4hu**
reported by https://issues.apache.org/jira/browse/KYLIN-3475

### CODE REVIEW

**Comment by ian4hu** [comment]
@shaofengshi Would you mind verifying this PR?

**Comment by shaofengshi** [comment]
Thanks Hu! We will run the integration test for this PR; Thanks!

**Comment by shaofengshi** [comment]
Compile and mvn test all good.

It looks good to me.

@liyang-gmt8 @rogercloud , please also take a review. Thanks!

**Comment by shaofengshi** [comment]
Hi Ian, we need the commit message started with JIRA ID, for example: "KYLIN-3475 Make calcite connection configurable". Please update the commit message. You can do that with "git rebase -i HEAD~1" in your branch. After the commit message be updated, re-push to your fork, this PR will be automatically refreshed.

Thanks!

**Comment by ian4hu** [comment]
@liyang-gmt8 done.

**Pull request merged**
