### PR TITLE
[KYLIN-4068] append limit and offset to sql reliably

### PR DESCRIPTION
**Pull request by weibin0516**
## What changes were proposed in this pull request?
Currently, there is a bug in sql conversion, as follow:

```sql
SELECT E_Name FROM Employees_China
UNION
SELECT E_Name FROM Employees_USA
```

will convert to

```sql
SELECT E_Name FROM Employees_China
UNION
SELECT E_Name FROM Employees_USA
LIMIT 50000
```

This limit is not working on the result of union, but on SELECT E_Name FROM Employees_USA.
We should use a more secure way to achieve the limit effect.

This pr fixed the bug, making sure to append limit or offset after sql does not change sql semantics

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by weibin0516** [comment]
@nichunen @hit-lacus Could you help review this pr? Thanks very much!

**Comment by hit-lacus** [comment]
IT test passed

**Comment by weibin0516** [comment]
@nichunen Could you help merge this pr? Code review and tests passed. Thanks~

**Pull request merged**
