### PR TITLE
satisfy multi-path of domain for kylin connection (against master)

### PR DESCRIPTION
**Pull request by study010**
So far, Kylin JDBC only satisfies domain/project pattern, but many companies use multi-path of domain. For example, domain/path/project. I improve this issue. @yiming187  Please review this issue.

### CODE REVIEW

**Comment by shaofengshi** [comment]
hello study010, thanks for the patch; as an Apache project, Kylin accept the contributions with a JIRA and then attaching the git patch file in it. Thanks for joining the community! See: https://kylin.apache.org/development/howto_contribute.html

**Comment by study010** [comment]
Thank you. @shaofengshi I am promoting Kylin actively and our project has used it. I will actively participate in Kylin's open source!

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hello @study010 , I'm reviewing this patch again, still curious about the scenario. You mentioned "many companies use multi-path of domain", could you please give a sample?

The URL in Kylin JDBC is not a Rest URL, its pattern is "jdbc:kylin//hostname/projectname"; When talking to Kylin, it will use "http://hostname:7070/kylin/api" as the endpoint. So in the URL, there is almost no case to have another "/".

Thanks for the feedback.

**Comment by study010** [comment]
@shaofengshi , when loading driver with 'jdbc:kylin//hostname/projectname', our company use domain and multi-path to indicate the hostname, which is to achieve workload balance. For example， jdbc:kylin//a.config.com/kylin/projectname.  If there is any doubt, please contact me in time

**Comment by shaofengshi** [comment]
@study010 I see now, thanks for the information!

**Comment by shaofengshi** [comment]
Please create a JIRA to track the issues, I created one for this PR: https://issues.apache.org/jira/browse/KYLIN-3422

Thanks for contribute to Kylin!

**Comment by study010** [comment]
@shaofengshi What should i do now.

**Pull request merged**
