### PR TITLE
KYLIN-3841 Build Global Dict by MR/Hive

### PR DESCRIPTION
**Pull request by javalife0312**
add steps:
1、Global Dict Mr/Hive extract dict_val from Data
2、Global Dict Mr/Hive build dict_val
3、Global Dict Mr/Hive replace dict_val to Data
optimize:
1、Extract Fact Table Distinct Columns reduce mr-hive-dict-column option
2、Build Dimension Dictionary reduce mr-hive-dict-column option
3、Build Base Cuboid reduce dict option

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by javalife0312** [comment]
Useage：
Configuration Overwrites
kylin.dictionary.mr-hive.columns ORDER_CITY_CITY_NAME
ORDER_CITY_CITY_NAME = tableAlias_columnName

**Comment by shaofengshi** [comment]
Hi Guowei, can you use seperated PR for the changes of count(col)? Thank you!

**Comment by javalife0312** [comment]
> Hi Guowei, can you use seperated PR for the changes of count(col)? Thank you!

ok

**Comment by nichunen** [comment]
Re-submit with pr https://github.com/apache/kylin/pull/568
close this one

**Pull request closed without merging**
