### PR TITLE
KYLIN-3594 Obey JDBC standard

### PR DESCRIPTION
**Pull request by hit-lacus**
https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-3594

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Please check the Jenkins error.

**Comment by narahari92** [comment]
Please add below test also, just to cover the multiple table scenario.
"select name, count(*) as cnt from defaultCatalog.test.kylin_sales inner join defaultCatalog.test.kylin_account ON kylin_sales.BUYER_ID=kylin_account.ACCOUNT_ID" 
should become 
"select name, count(*) as cnt from test.kylin_sales inner join test.kylin_account ON kylin_sales.BUYER_ID=kylin_account.ACCOUNT_ID"

**Comment by hit-lacus** [comment]
@narahari92 OK

**Comment by shaofengshi** [comment]
Please also test the column name be the full qualified format, like schema.table.col.

**Pull request merged**
