### PR TITLE
KYLIN-4547 parse crc file error when building cube with mapreduce

### PR DESCRIPTION
**Pull request by qin7972**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [x] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I will prepare another pr against the `document` branch
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by shaofengshi** [comment]
How does the crc file come? If it is not by kylin, then I think you need to find the root cause, instead of adding the filter.

**Comment by qin7972** [comment]
> How does the crc file come? If it is not by kylin, then I think you need to find the root cause, instead of adding the filter.

**Comment by qin7972** [comment]
@shaofengshi 
The crc file comes from hdfs.The path:
${yarn.nodemanager.local-dirs}/usercache/root/appcache/application_1591713180468_0013/container_1591713180468_0013_01_000001/meta

This error does not appear in kylin 2.5.1. 
Because kylin's CachedCrudAssist loads resources from the directory, it uses the json suffix rule to match the file, the file with the crc suffix is filtered out.
Then the JsonSerializer is used to deserialize the files that meet the conditions, so there will be no problems.

However, in kylin 3.0.0, CachedCrudAssis first scans all files in the directory, and deserializes at the same time. 
The file with the suffix crc is deserialized by JsonSerializer to report this error. 
After the scan is complete, use the json suffix rule to match the file name.

Our pr refer to kylin 2.5.1, which is to add Filter to sink and filter out the files with crc suffix.

**Comment by LingangJiang** [comment]
How about this issue?  Although mapreduce job is success, but error in log

**Comment by LingangJiang** [comment]
this issue also appear in flink job engine

**Pull request closed without merging**
