### PR TITLE
KYLIN-3864 Provide a function to judge whether the os type is Mac os x or not

### PR DESCRIPTION
**Pull request by yanghua**
JIRA ref : https://issues.apache.org/jira/browse/KYLIN-3864

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hi Hua, which script will use this?

**Comment by yanghua** [comment]
Hi @shaofengshi  Now, In kylin project, there are many places where the code would check the os type is **Darwin** (Mac os X) such as `download-spark.sh`, `download-flink.sh`, `tool-wrapper.sh`. And there are some places where Kylin is not compatible with Mac os X (it does not check the os type), it caused some errors, such as [KYLIN-3756](https://issues.apache.org/jira/browse/KYLIN-3756) and [KYLIN-3757](https://issues.apache.org/jira/browse/KYLIN-3757). This util method provides a general function to verify whether the current os type is Mac os X or not.

By providing this function, we can do generic checking for the different `like-UNIX` os, and fix those compatible issues existing in the shell script.

**Comment by shaofengshi** [comment]
I see, there will be subsequent changes based on this. I will merge it.

**Pull request merged**
