### PR TITLE
KYLIN-4224 Create flat table wich spark sql

### PR DESCRIPTION
**Pull request by weibin0516**

### CODE REVIEW

**Comment by weibin0516** [comment]
@nichunen @hit-lacus Could you help review this pr, thanks!

**Comment by nichunen** [comment]
@weibin0516 OK!

**Comment by nichunen** [comment]
@weibin0516 Seems YARN_APP_URL not added to the step

**Comment by RupengWang** [comment]
### Check list
- [ ] Step 1. [**OPTIONAL**]Understand background/root cause/design basically(one hour EST) . Its issue type is 
    - [ ] bug fix
    - [ ] new feature
    - [ ] enhancement
- [ ] Step 2. Test cases are designed and documented (30 minutes EST).
- [ ] Step 3. Prepare specific env, for example:
    - mock data (maybe some specific data type)
    - test env (maybe install a RDBMS instance).
- [ ] Step 4. Verify and make sure test cases passed.
- [ ] Step 5. Paste manual important steps and screenshots here (20 minutes EST). 
    - If you find difficulty in pick most important evidence, please attach diagnosis package. 
- [ ] Step 6. Do more check in user perspective (20 minutes EST)
    - [ ] Doc need be updated? And if it is updated? Ask help for release manager if so.
    - [ ] If it is a breaking change so we should notify Kylin community? Ask help for release manager if so.
- [ ] Step 7.  Summarize this test (20 minutes EST).

### Total estimate
- 4 hours for small issue from optimistic estimate. 

### Note
If you find some unexpected and **unrelated** error/mistake, please DO report it if it is truly a mistake, I think we may research and fix it in the future.

If you find background information/root cause analysis is not complete or ambiguous, please try to contact to author or do a quick research and record what you find. It is a good chance to learn something interesting.

If you find it is not easy to design testcase, please notify release manager.

**Comment by RupengWang** [comment]
## Design test cases

### Prepare test env
Kylin sample cube

### Case-1
Set 'kylin.engine.spark-create-table-enabled=true' in kylin.properties

**Comment by RupengWang** [comment]
## Prepare data and env

- [x] Built on commit_SHA : ae6120b849c499956a11814d817fb9506e6dd2d6
- [x] Hadoop env : HDP 2.4

- [x] Just sample cube is OK.
image

**Comment by RupengWang** [comment]
## Verify test case

#### Case-1

**Comment by RupengWang** [comment]
### Unexpected bug report

1. Container exit with error
- Detail log
```log
Diagnostics: Exception from container-launch.
Container id: container_e05_1585051378273_14708_02_000001
Exit code: 1
Exception message: /hadoop/yarn/local/usercache/root/appcache/application_1585051378273_14708/container_e05_1585051378273_14708_02_000001/launch_container.sh: line 16: $PWD:$PWD/__spark_conf__:$PWD/__spark_libs__/*:$HADOOP_CONF_DIR:/usr/hdp/current/hadoop-client/*:/usr/hdp/current/hadoop-client/lib/*:/usr/hdp/current/hadoop-hdfs-client/*:/usr/hdp/current/hadoop-hdfs-client/lib/*:/usr/hdp/current/hadoop-yarn-client/*:/usr/hdp/current/hadoop-yarn-client/lib/*:$PWD/mr-framework/hadoop/share/hadoop/mapreduce/*:$PWD/mr-framework/hadoop/share/hadoop/mapreduce/lib/*:$PWD/mr-framework/hadoop/share/hadoop/common/*:$PWD/mr-framework/hadoop/share/hadoop/common/lib/*:$PWD/mr-framework/hadoop/share/hadoop/yarn/*:$PWD/mr-framework/hadoop/share/hadoop/yarn/lib/*:$PWD/mr-framework/hadoop/share/hadoop/hdfs/*:$PWD/mr-framework/hadoop/share/hadoop/hdfs/lib/*:$PWD/mr-framework/hadoop/share/hadoop/tools/lib/*:/usr/hdp/${hdp.version}/hadoop/lib/hadoop-lzo-0.6.0.${hdp.version}.jar:/etc/hadoop/conf/secure:$PWD/__spark_conf__/__hadoop_conf__: bad substitution
```
- Reason
hdp.version not set in kylin.properties

**Pull request merged**
