### PR TITLE
Added Chinese documentation of how_to

### PR DESCRIPTION
**Pull request by link3280**
Translated several how_to docs into Chinese.

### CODE REVIEW

**Comment by yiming187** [comment]
great contribution, thanks @link3280

**Comment by yiming187** [comment]
Hi @link3280 https://issues.apache.org/jira/browse/KYLIN-3198 is created for this PR. I will merge it into document branch with a little updates. I'd like to mark you as the JIRA owner. Could you leave your ID in the JIRA?

**Comment by link3280** [comment]
Yes, of course. My JIRA ID is "Paul Lin". Thanks!

**Comment by yiming187** [comment]
Thanks @link3280 . JIRA updated. Please close this PR.

**Pull request closed without merging**
