### PR TITLE
KYLIN-3958 MrHive-Dict support build by livy

### PR DESCRIPTION
**Pull request by javalife0312**
https://issues.apache.org/jira/browse/KYLIN-3958?filter=-1
build steps：
1、Build Global Dict - extract distinct 
2、Build Global Dict - merge to dict table
3、Build Global Dict - replace 
4、Redistribute Flat Hive Table
by livy if 【kylin.engine.livy-conf.livy-enabled=true】

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by hit-lacus** [comment]
image


```java
2019-05-17 11:59:55,665 ERROR [http-bio-7172-exec-10] controller.CubeController:397 : -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.apache.kylin.source.hive.MRHiveDictUtil.generateInsertDataStatement(MRHiveDictUtil.java:103)
	at org.apache.kylin.source.hive.HiveInputBase$BaseBatchCubingInputSide.createMrHiveGlobalDictExtractStep(HiveInputBase.java:149)
	at org.apache.kylin.source.hive.HiveInputBase$BaseBatchCubingInputSide.addStepPhase1_DoCreateMrHiveGlobalDict(HiveInputBase.java:127)
	at org.apache.kylin.source.hive.HiveInputBase$BaseBatchCubingInputSide.addStepPhase1_CreateFlatTable(HiveInputBase.java:101)
	at org.apache.kylin.engine.mr.BatchCubingJobBuilder2.build(BatchCubingJobBuilder2.java:59)
	at org.apache.kylin.engine.mr.MRBatchCubingEngine2.createBatchCubingJob(MRBatchCubingEngine2.java:42)
	at org.apache.kylin.engine.EngineFactory.createBatchCubingJob(EngineFactory.java:61)
	at org.apache.kylin.rest.service.JobService.submitJobInternal(JobService.java:240)
	at org.apache.kylin.rest.service.JobService.submitJob(JobService.java:208)
	at org.apache.kylin.rest.controller.CubeController.buildInternal(CubeController.java:394)
	at org.apache.kylin.rest.controller.CubeController.rebuild(CubeController.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
```

**Comment by hit-lacus** [comment]
error when create flat table
``` sh
== SQL ==
CREATE EXTERNAL TABLE IF NOT EXISTS kylin_intermediate_kylinsalesmrdictcube_spark_09819960_2b46_020d_c682_b314e7bdb162 (  bigint , date , bigint , bigint , string , bigint , int , string , string , decimal(19,4) , bigint , string , string ) STORED AS SEQUENCEFILE LOCATION 'hdfs://cdh1.cloudera.com:8020/kylin/kylin_metadata3958/kylin-ae922ad6-43cd-5570-e2e8-f2dae8bad1fc/kylin_intermediate_kylinsalesmrdictcube_spark_09819960_2b46_020d_c682_b314e7bdb162'
---------------------------------------------------------------------------------------------------------------------------------^^^

org.apache.spark.sql.catalyst.parser.ParseException:
no viable alternative at input 'CREATE EXTERNAL TABLE IF NOT EXISTS kylin_intermediate_kylinsalesmrdictcube_spark_09819960_2b46_020d_c682_b314e7bdb162 (  bigint ,'(line 1, pos 129)
```

**Comment by nichunen** [comment]
Re-submit with https://github.com/apache/kylin/pull/648, close this one

**Pull request closed without merging**
