### PR TITLE
Added Unit Tests

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added Unit Tests to increase code coverage.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by nichunen** [comment]
Hi @TheRealHaui 

The pr is not passed by style check, for "Using the '.*' form of import should be avoided"

**Comment by TheRealHaui** [comment]
Hi,
thanks for the advice.
I know.
Already fixed it but oversaw that my IDE integrated a star import for JUnit assert statements on saving.
Going to fix it again.
After trying to teach my IDE to not integrate star imports in the background on saving again.

**Comment by TheRealHaui** [comment]
@nichunen,
now it is passing.

**Pull request merged**
