### PR TITLE
KYLIN-2924 enable google error-prone in compile phase

### PR DESCRIPTION
**Pull request by yiming187**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
The travis-ci is failed with "The job exceeded the maximum log length, and has been terminated."

**Comment by yiming187** [comment]
@shaofengshi yes. I saw it. I have fixed all "ERROR" level issues, but the "WARNING" issues generated too much logs. Trying to ignore the "WARNING" log to reduce the output size.

**Pull request merged**
