### PR TITLE
KYLIN-3597 Fix sonar reported static code issues

### PR DESCRIPTION
**Pull request by Wayne1c**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Chao, please check and make travis-ci passed.

**Comment by Wayne1c** [comment]
Travis-ci passed.

**Comment by yiming187** [comment]
LGTM. Merged

**Pull request merged**
