### PR TITLE
[KYLIN-4554] validate filter condition on model saving

### PR DESCRIPTION
**Pull request by zheniantoushipashi**
verify filter condition using the following login

1 select * from tableName where {filterCondition} pass   calcite  parse

2 all column in filter condition must be model table column

### CODE REVIEW

**Comment by hit-lacus** [comment]
Did you patch consider dynamic variable case?


image

**Comment by zheniantoushipashi** [comment]
**test evidence** 


**Positive testing**

Use ssb data set， create a  data model,    add filter LO_CUSTKEY > 1  at  last step 

Successfully created the model

image


**Negative Testing** 

Add an additional Y after the LO_CUSTKEY column to construct a column ：LO_CUSTKEYY   that does not belong to the model table

image

The following error is reported when saving the model

Failed to deal with the request: java.lang.IllegalArgumentException: filter condition col: LO_CUSTKEYY is not a column in the table

Meet the test expectations

**Comment by zheniantoushipashi** [comment]
> Did you patch consider dynamic variable case? Like `date_str>='${start_date}' and date_str<'${end_date}'` .
> 
> image

thanks for reminding，  When saving the model, use the start_date and end_date of a mock to replace sql, and then verify

see the below test evidence

image

**Comment by hit-lacus** [comment]
Maybe we can make it more Robust?

I change your UT a little, by changing from `TRANS_ID` to `kylin_account.TRANS_ID`, and find a mistake.

```java
deserialize.setFilterCondition("kylin_account.TRANS_ID = 1");
```

Following is the debug mode, it indicates that `allSqlIdentifier.add(id.names.get(0));` return `kylin_account`, not column name.

image

I think it could be better implemented, am I right ?

**Comment by hit-lacus** [comment]
Besides, I think columns in dimension table should also be taken into account.

**Review by hit-lacus — CHANGES_REQUESTED** [review]
-1
I think more cases should be considered. Do you agreed?

**Comment by zheniantoushipashi** [comment]
retest this please 

> Maybe we can make it more Robust?
> 
> I change your UT a little, by changing from `TRANS_ID` to `kylin_account.TRANS_ID`, and find a mistake.
> 
> ```java
> deserialize.setFilterCondition("kylin_account.TRANS_ID = 1");
> ```
> 
> Following is the debug mode, it indicates that `allSqlIdentifier.add(id.names.get(0));` return `kylin_account`, not column name.
> 
> image
> 
> I think it could be better implemented, am I right ?

yes, you are right, should consider it

**Comment by zheniantoushipashi** [comment]
I added all the columns of all tables to the validate collection,  I did verification in ut and integration tests,

**test evidence**

image


image

**Review by hit-lacus — APPROVED** [review]
LGTM

**Comment by hit-lacus** [comment]
Since that the version 3.1.2 is going to releasing, I would merge any new code change  at the moment. I will merge it after 3.1.2 is released. 

Thanks for your first contribution, @zheniantoushipashi please go ahead!

**Comment by zheniantoushipashi** [comment]
retest this please

**Pull request merged**
