### PR TITLE
Added blog entry describing how to connect e.g. Tableau to Apache Kylin

### PR DESCRIPTION
**Pull request by pnaszarkowski**
…t Tableau with Kylin

### CODE REVIEW

**Comment by pnaszarkowski** [comment]
To be reviewed by @shaofengshi ?

**Comment by pnaszarkowski** [comment]
@shaofengshi I see some formatting issues on the blog after publishing (https://kylin.apache.org/blog/2019/09/22/kylin-tableau/), please take a look and let me know if that should be fixed in the blog entry or website engine?
- 3rd and 4th level sections' titles are not rendered correctly
image

- numbering is broken when numbered points contain images
image

**Comment by shaofengshi** [comment]
In my local preview with Jekyll, they appeared good; anyway, I inserted a blank line there to see whether it has any change.

屏幕快照 2019-09-29 下午9 35 20
屏幕快照 2019-09-29 下午9 46 41

**Comment by pnaszarkowski** [comment]
@shaofengshi @nichunen - thanks for fixing this, blog entry looks OK now :)

**Pull request merged**
