### PR TITLE
[KYLIN-4947] Implement spark engine for cube optimization jobs.

### PR DESCRIPTION
**Pull request by Ted-Jiang**
## Proposed changes

 Implement spark engine for cube optimization jobs.

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [ ] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I will prepare another pr against the `document` branch
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zhangayqian — CHANGES_REQUESTED** [review]
I tested this patch, and in step `Merge Cuboid Statistics with Old for Optimization` of optimize job, the following changes occurred:
```
java.io.IOException: StatisticsFilePath hdfs://cdh-master:8020/kylin/yaqian/kylin_metadata_test_new/kylin-130f6bfd-5a8e-3209-cb3c-c339d772f11d/kylin_sales_cube/optimize/statistics does not exists
 at org.apache.kylin.engine.mr.steps.MergeStatisticsWithOldStep.doWork(MergeStatisticsWithOldStep.java:82)
 at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:180)
 at org.apache.kylin.job.execution.DefaultChainedExecutable.doWork(DefaultChainedExecutable.java:72)
 at org.apache.kylin.job.execution.AbstractExecutable.execute(AbstractExecutable.java:180)
 at org.apache.kylin.job.impl.threadpool.DefaultScheduler$JobRunner.run(DefaultScheduler.java:118)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
```

**Comment by Ted-Jiang** [comment]
thks, fix  @zhangayqian

**Comment by Ted-Jiang** [comment]
new fix @zhangayqian

**Review by zhangayqian — APPROVED** [review]

**Comment by Ted-Jiang** [comment]
@zhangayqian  fix. Thanks a lot !

**Comment by hit-lacus** [comment]
Thanks @Ted-Jiang !

**Pull request merged**
