### PR TITLE
add the compatibility for new version of hbase

### PR DESCRIPTION
**Pull request by wankunde**
Newly hbase version add some new method in  `Table` and `ResultScanner` interface.
So we should add the implementation method.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hello Wankunde, 

Could you please create a JIRA to describe this change? For example: https://issues.apache.org/jira/browse/KYLIN-3168

**Comment by wankunde** [comment]
Hi,shaofengshi,
I just created a issue : https://issues.apache.org/jira/browse/KYLIN-3367

**Comment by shaofengshi** [comment]
Merged in Kylin master branch, so close this PR.

**Pull request closed without merging**
