### PR TITLE
KYLIN-4287  SegmenPruner cannot prune segment exactly when handle 'IN' filter

### PR DESCRIPTION
**Pull request by zhangbushi5**

### CODE REVIEW

**Comment by nichunen** [comment]
@zhangbushi5 Would you please add a ut in SegmentPrunerTest?

**Comment by RupengWang** [comment]
### Check list
- [x] Step 1. [**OPTIONAL**]Understand background/root cause/design basically(one hour EST) . Its issue type is 
    - [ ] bug fix
    - [ ] new feature
    - [x] enhancement
- [x] Step 2. Test cases are designed and documented (30 minutes EST).
- [x] Step 3. Prepare specific env, for example:
    - mock data (maybe some specific data type)
    - test env (maybe install a RDBMS instance).
- [x] Step 4. Verify and make sure test cases passed.
- [x] Step 5. Paste manual important steps and screenshots here (20 minutes EST). 
    - If you find difficulty in pick most important evidence, please attach diagnosis package. 
- [x] Step 6. Do more check in user perspective (20 minutes EST)
    - [x] Doc need be updated? And if it is updated? Ask help for release manager if so.
    - [x] If it is a breaking change so we should notify Kylin community? Ask help for release manager if so.
- [x] Step 7.  Summarize this test (20 minutes EST).

### Total estimate
- 4 hours for small issue from optimistic estimate. 

### Note
If you find some unexpected and **unrelated** error/mistake, please DO report it if it is truly a mistake, I think we may research and fix it in the future.

If you find background information/root cause analysis is not complete or ambiguous, please try to contact to author or do a quick research and record what you find. It is a good chance to learn something interesting.

If you find it is not easy to design testcase, please notify release manager.

**Comment by RupengWang** [comment]
## Design test cases

### Prepare test env
- Using kylin sample cube - kylin_salesa_cube
- build segment[2012-01-01 ~ 2012-02-01] and segment[2012-02-01 ~ 2012-06-01]

### Case-1
```sql
select count(*) from kylin_sales where part_dt = '2012-01-01' OR part_dt = '2012-08-01'
```
2020-06-15 16:56:42,913 DEBUG [Query 3fe1e44b-4ad9-76a2-9693-1dc6f0233aeb-66] common.SegmentPruner:79 : Pruner passed on segment kylin_sales_cube[20120101000000_20120201000000]
2020-06-15 16:56:42,914 DEBUG [Query 3fe1e44b-4ad9-76a2-9693-1dc6f0233aeb-66] common.SegmentPruner:75 : Prune segment kylin_sales_cube[20120201000000_20120601000000] due to given filter
### Case-2
```sql
select count(*) from kylin_sales where part_dt in ('2012-01-01', '2012-01-02','2012-08-02')
```
2020-06-15 17:10:45,369 DEBUG [Query c8bdbe0f-2d79-7002-3032-44a86590a97e-68] common.SegmentPruner:79 : Pruner passed on segment kylin_sales_cube[20120101000000_20120201000000]
2020-06-15 17:10:45,369 DEBUG [Query c8bdbe0f-2d79-7002-3032-44a86590a97e-68] common.SegmentPruner:75 : Prune segment kylin_sales_cube[20120201000000_20120601000000] due to given filter

**Comment by RupengWang** [comment]
## Prepare data and env

- [x] Built on commit_SHA : 2b29166786cfa4fb3e4cb3b444a06df6257cf21d
- [x] Hadoop env : CDH 5.7
- [x] Just sample cube is OK.
image

**Comment by RupengWang** [comment]
## Verify test case
#### Case-1
```log
2020-06-15 16:56:42,913 DEBUG [Query 3fe1e44b-4ad9-76a2-9693-1dc6f0233aeb-66] common.SegmentPruner:79 : Pruner passed on segment kylin_sales_cube[20120101000000_20120201000000]
2020-06-15 16:56:42,914 DEBUG [Query 3fe1e44b-4ad9-76a2-9693-1dc6f0233aeb-66] common.SegmentPruner:75 : Prune segment kylin_sales_cube[20120201000000_20120601000000] due to given filter
```

#### Case-2
```log
2020-06-15 17:10:45,369 DEBUG [Query c8bdbe0f-2d79-7002-3032-44a86590a97e-68] common.SegmentPruner:79 : Pruner passed on segment kylin_sales_cube[20120101000000_20120201000000]
2020-06-15 17:10:45,369 DEBUG [Query c8bdbe0f-2d79-7002-3032-44a86590a97e-68] common.SegmentPruner:75 : Prune segment kylin_sales_cube[20120201000000_20120601000000] due to given filter
```

**Pull request merged**
