### PR TITLE
KYLIN-3379 fix ts add bug and enhance the test coverage of timestamp add.

### PR DESCRIPTION
**Pull request by tttMelody**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hi Jiatao, the CI is failed, you will update the PR right?

**Comment by tttMelody** [comment]
@shaofengshi Thanks shaofeng, something wrong with timestamp add, I pushed the fix and retriggered CI.

**Comment by tttMelody** [comment]
Hi @shaofengshi, CI passed.

**Pull request merged**
