### PR TITLE
KYLIN-4771 Clear the recordCachePool when the deadline has reached

### PR DESCRIPTION
**Pull request by ggKe**
## Proposed changes

1、Clear the recordCachePool when the deadline has reached.
2、Add timeout for the recordCachePool offer.
https://issues.apache.org/jira/projects/KYLIN/issues/KYLIN-4771?filter=reportedbyme

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

### CODE REVIEW

**Comment by ggKe** [comment]
This modification is currently working well in our work.

**Comment by hit-lacus** [comment]
Hello @ggKe , I have checked your patch, your patch look good to me. But there are some UT failure, could you please help to fix them? 

Following is part of log:


```sh
[[1;34mINFO[m] [1;32mTests run: [0;1;32m1[m, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.242 s - in org.apache.kylin.stream.core.storage.[1mRecordsSerDeTest[m
[[1;34mINFO[m] Running org.apache.kylin.stream.core.storage.[1mCheckPointStoreTest[m
client:0 round266 scan finished
client:1 round269 scan finished
CheckPoint{sourceConsumePosition='{"1":30000,"2":40000,"3":50000}', persistedIndexes={1602241200000=1, 1602241199999=2, 1602241199998=3}, longLatencyInfo=LongLatencyInfo{longLatencyEventCnts={}, totalLongLatencyEventCnt=0}, segmentSourceStartPosition={1602241200000={"1":10000,"2":20000,"3":30000}}, checkPointTime=1602242847871, totalCount=1000000, checkPointCount=50000}
going to delete checkpoint file CP-1602201600000
going to delete checkpoint file CP-1602288000000
going to delete checkpoint file CP-1602374400000
going to delete checkpoint file CP-1602460800000
going to delete checkpoint file CP-1602547200000
CheckPoint{sourceConsumePosition='{"1":10000,"2":20000,"3":30000}', persistedIndexes={1602241200000=1, 1602241199999=2, 1602241199998=3}, longLatencyInfo=LongLatencyInfo{longLatencyEventCnts={}, totalLongLatencyEventCnt=0}, segmentSourceStartPosition={1602241200000={"1":10000,"2":20000,"3":30000}}, checkPointTime=1603020447894, totalCount=1000000, checkPointCount=50000}
[[1;34mINFO[m] [1;32mTests run: [0;1;32m3[m, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s - in org.apache.kylin.stream.core.storage.[1mCheckPointStoreTest[m
[[1;34mINFO[m] 
[[1;34mINFO[m] Results:
[[1;34mINFO[m] 
[[1;31mERROR[m] [1;31mFailures: [m
[[1;31mERROR[m] [1;31m  StreamingSegmentManagerTest.testAddEventAndScan:120 expected:<80000> but was:<30007>[m
[[1;31mERROR[m] [1;31m  StreamingSegmentManagerTest.testIndexFilter:182 expected:<153298[080]0000> but was:<153298[104]0000>[m
[[1;34mINFO[m] 
[[1;31mERROR[m] [1;31mTests run: 29, Failures: 2, Errors: 0, Skipped: 0[m
[[1;34mINFO[m] 
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1mSkipping Apache Kylin[m
[[1;34mINFO[m] This project has been banned from the build due to previous failures.
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1mReactor Summary:[m
[[1;34mINFO[m] 
[[1;34mINFO[m] Apache Kylin 3.1.1-SNAPSHOT ........................ [1;32mSUCCESS[m [  3.516 s]
[[1;34mINFO[m] Apache Kylin - kylin External ...................... [1;32mSUCCESS[m [  9.946 s]
[[1;34mINFO[m] Apache Kylin - Core Common ......................... [1;32mSUCCESS[m [ 22.354 s]
[[1;34mINFO[m] Apache Kylin - Core Metadata ....................... [1;32mSUCCESS[m [ 48.745 s]
[[1;34mINFO[m] Apache Kylin - Core Dictionary ..................... [1;32mSUCCESS[m [03:16 min]
[[1;34mINFO[m] Apache Kylin - Core Cube ........................... [1;32mSUCCESS[m [02:19 min]
[[1;34mINFO[m] Apache Kylin - Core Metrics ........................ [1;32mSUCCESS[m [  5.364 s]
[[1;34mINFO[m] Apache Kylin - Core Job ............................ [1;32mSUCCESS[m [01:08 min]
[[1;34mINFO[m] Apache Kylin - Core Storage ........................ [1;32mSUCCESS[m [  9.280 s]
[[1;34mINFO[m] Apache Kylin - Stream Core ......................... [1;31mFAILURE[m [01:02 min]
[[1;34mINFO[m] Apache Kylin - MapReduce Engine .................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Spark Engine ........................ [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Flink Engine ........................ [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Hive Source ......................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - DataSource SDK ...................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Jdbc Source ......................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Kafka Source ........................ [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Cache ............................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - HBase Storage ....................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Query ............................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Metrics Reporter Hive ............... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Metrics Reporter Kafka .............. [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Stream Source Kafka ................. [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Stream Coordinator .................. [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Stream Receiver ..................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Stream Storage ...................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - REST Server Base .................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Tool ................................ [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Cube Migration Service .............. [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - REST Server ......................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - JDBC Driver ......................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Assembly ............................ [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Tool Assembly ....................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Integration Test .................... [1;33mSKIPPED[m
[[1;34mINFO[m] Apache Kylin - Tomcat Extension 3.1.1-SNAPSHOT ..... [1;33mSKIPPED[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time: 09:28 min
[[1;34mINFO[m] Finished at: 2020-10-09T11:27:28Z
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.21.0:test[m [1m(default-test)[m on project [36mkylin-stream-core[m: [1;31mThere are test failures.[m
[[1;31mERROR[m] [1;31m[m
[[1;31mERROR[m] [1;31mPlease refer to /home/travis/build/apache/kylin/stream-core/../target/surefire-reports for the individual test results.[m
[[1;31mERROR[m] [1;31mPlease refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.[m
[[1;31mERROR[m] -> [1m[Help 1][m
[1;31morg.apache.maven.lifecycle.LifecycleExecutionException[m: [1;31mFailed to execute goal [32morg.apache.maven.plugins:maven-surefire-plugin:2.21.0:test[m [1m(default-test)[m on project [36mkylin-stream-core[m: [1;31mThere are test failures.
```

**Comment by ggKe** [comment]
> Hello @ggKe , I have checked your patch, your patch look good to me. But there are some UT failure, could you please help to fix them?
> 
> Following is part of log:
> 
> ```
> [�[1;34mINFO�[m] �[1;32mTests run: �[0;1;32m1�[m, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.242 s - in org.apache.kylin.stream.core.storage.�[1mRecordsSerDeTest�[m
> [�[1;34mINFO�[m] Running org.apache.kylin.stream.core.storage.�[1mCheckPointStoreTest�[m
> client:0 round266 scan finished
> client:1 round269 scan finished
> CheckPoint{sourceConsumePosition='{"1":30000,"2":40000,"3":50000}', persistedIndexes={1602241200000=1, 1602241199999=2, 1602241199998=3}, longLatencyInfo=LongLatencyInfo{longLatencyEventCnts={}, totalLongLatencyEventCnt=0}, segmentSourceStartPosition={1602241200000={"1":10000,"2":20000,"3":30000}}, checkPointTime=1602242847871, totalCount=1000000, checkPointCount=50000}
> going to delete checkpoint file CP-1602201600000
> going to delete checkpoint file CP-1602288000000
> going to delete checkpoint file CP-1602374400000
> going to delete checkpoint file CP-1602460800000
> going to delete checkpoint file CP-1602547200000
> CheckPoint{sourceConsumePosition='{"1":10000,"2":20000,"3":30000}', persistedIndexes={1602241200000=1, 1602241199999=2, 1602241199998=3}, longLatencyInfo=LongLatencyInfo{longLatencyEventCnts={}, totalLongLatencyEventCnt=0}, segmentSourceStartPosition={1602241200000={"1":10000,"2":20000,"3":30000}}, checkPointTime=1603020447894, totalCount=1000000, checkPointCount=50000}
> [�[1;34mINFO�[m] �[1;32mTests run: �[0;1;32m3�[m, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 s - in org.apache.kylin.stream.core.storage.�[1mCheckPointStoreTest�[m
> [�[1;34mINFO�[m] 
> [�[1;34mINFO�[m] Results:
> [�[1;34mINFO�[m] 
> [�[1;31mERROR�[m] �[1;31mFailures: �[m
> [�[1;31mERROR�[m] �[1;31m  StreamingSegmentManagerTest.testAddEventAndScan:120 expected:<80000> but was:<30007>�[m
> [�[1;31mERROR�[m] �[1;31m  StreamingSegmentManagerTest.testIndexFilter:182 expected:<153298[080]0000> but was:<153298[104]0000>�[m
> [�[1;34mINFO�[m] 
> [�[1;31mERROR�[m] �[1;31mTests run: 29, Failures: 2, Errors: 0, Skipped: 0�[m
> [�[1;34mINFO�[m] 
> [�[1;34mINFO�[m] 
> [�[1;34mINFO�[m] �[1m------------------------------------------------------------------------�[m
> [�[1;34mINFO�[m] �[1mSkipping Apache Kylin�[m
> [�[1;34mINFO�[m] This project has been banned from the build due to previous failures.
> [�[1;34mINFO�[m] �[1m------------------------------------------------------------------------�[m
> [�[1;34mINFO�[m] �[1m------------------------------------------------------------------------�[m
> [�[1;34mINFO�[m] �[1mReactor Summary:�[m
> [�[1;34mINFO�[m] 
> [�[1;34mINFO�[m] Apache Kylin 3.1.1-SNAPSHOT ........................ �[1;32mSUCCESS�[m [  3.516 s]
> [�[1;34mINFO�[m] Apache Kylin - kylin External ...................... �[1;32mSUCCESS�[m [  9.946 s]
> [�[1;34mINFO�[m] Apache Kylin - Core Common ......................... �[1;32mSUCCESS�[m [ 22.354 s]
> [�[1;34mINFO�[m] Apache Kylin - Core Metadata ....................... �[1;32mSUCCESS�[m [ 48.745 s]
> [�[1;34mINFO�[m] Apache Kylin - Core Dictionary ..................... �[1;32mSUCCESS�[m [03:16 min]
> [�[1;34mINFO�[m] Apache Kylin - Core Cube ........................... �[1;32mSUCCESS�[m [02:19 min]
> [�[1;34mINFO�[m] Apache Kylin - Core Metrics ........................ �[1;32mSUCCESS�[m [  5.364 s]
> [�[1;34mINFO�[m] Apache Kylin - Core Job ............................ �[1;32mSUCCESS�[m [01:08 min]
> [�[1;34mINFO�[m] Apache Kylin - Core Storage ........................ �[1;32mSUCCESS�[m [  9.280 s]
> [�[1;34mINFO�[m] Apache Kylin - Stream Core ......................... �[1;31mFAILURE�[m [01:02 min]
> [�[1;34mINFO�[m] Apache Kylin - MapReduce Engine .................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Spark Engine ........................ �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Flink Engine ........................ �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Hive Source ......................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - DataSource SDK ...................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Jdbc Source ......................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Kafka Source ........................ �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Cache ............................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - HBase Storage ....................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Query ............................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Metrics Reporter Hive ............... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Metrics Reporter Kafka .............. �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Stream Source Kafka ................. �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Stream Coordinator .................. �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Stream Receiver ..................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Stream Storage ...................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - REST Server Base .................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Tool ................................ �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Cube Migration Service .............. �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - REST Server ......................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - JDBC Driver ......................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Assembly ............................ �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Tool Assembly ....................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Integration Test .................... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] Apache Kylin - Tomcat Extension 3.1.1-SNAPSHOT ..... �[1;33mSKIPPED�[m
> [�[1;34mINFO�[m] �[1m------------------------------------------------------------------------�[m
> [�[1;34mINFO�[m] �[1;31mBUILD FAILURE�[m
> [�[1;34mINFO�[m] �[1m------------------------------------------------------------------------�[m
> [�[1;34mINFO�[m] Total time: 09:28 min
> [�[1;34mINFO�[m] Finished at: 2020-10-09T11:27:28Z
> [�[1;34mINFO�[m] �[1m------------------------------------------------------------------------�[m
> [�[1;31mERROR�[m] Failed to execute goal �[32morg.apache.maven.plugins:maven-surefire-plugin:2.21.0:test�[m �[1m(default-test)�[m on project �[36mkylin-stream-core�[m: �[1;31mThere are test failures.�[m
> [�[1;31mERROR�[m] �[1;31m�[m
> [�[1;31mERROR�[m] �[1;31mPlease refer to /home/travis/build/apache/kylin/stream-core/../target/surefire-reports for the individual test results.�[m
> [�[1;31mERROR�[m] �[1;31mPlease refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.�[m
> [�[1;31mERROR�[m] -> �[1m[Help 1]�[m
> �[1;31morg.apache.maven.lifecycle.LifecycleExecutionException�[m: �[1;31mFailed to execute goal �[32morg.apache.maven.plugins:maven-surefire-plugin:2.21.0:test�[m �[1m(default-test)�[m on project �[36mkylin-stream-core�[m: �[1;31mThere are test failures.
> ```

hi,@hit-lacus,I have fixed the code , project can successfuly pass the UT now.
[INFO] Apache Kylin ....................................... SUCCESS [  3.201 s]
[INFO] Apache Kylin - kylin External ...................... SUCCESS [  6.257 s]
[INFO] Apache Kylin - Core Common ......................... SUCCESS [ 19.132 s]
[INFO] Apache Kylin - Core Metadata ....................... SUCCESS [ 48.198 s]
[INFO] Apache Kylin - Core Dictionary ..................... SUCCESS [09:10 min]
[INFO] Apache Kylin - Core Cube ........................... SUCCESS [02:12 min]
[INFO] Apache Kylin - Core Metrics ........................ SUCCESS [  5.826 s]
[INFO] Apache Kylin - Core Job ............................ SUCCESS [01:08 min]
[INFO] Apache Kylin - Core Storage ........................ SUCCESS [  7.384 s]
[INFO] Apache Kylin - Stream Core ......................... SUCCESS [ 46.880 s]
[INFO] Apache Kylin - MapReduce Engine .................... SUCCESS [ 46.244 s]
[INFO] Apache Kylin - Spark Engine ........................ SUCCESS [ 14.603 s]
[INFO] Apache Kylin - Flink Engine ........................ SUCCESS [ 10.946 s]
[INFO] Apache Kylin - Hive Source ......................... SUCCESS [  8.388 s]
[INFO] Apache Kylin - DataSource SDK ...................... SUCCESS [ 11.289 s]
[INFO] Apache Kylin - Jdbc Source ......................... SUCCESS [ 18.348 s]
[INFO] Apache Kylin - Kafka Source ........................ SUCCESS [  6.703 s]
[INFO] Apache Kylin - Cache ............................... SUCCESS [  9.287 s]
[INFO] Apache Kylin - HBase Storage ....................... SUCCESS [ 35.486 s]
[INFO] Apache Kylin - Query ............................... SUCCESS [ 13.792 s]
[INFO] Apache Kylin - Metrics Reporter Hive ............... SUCCESS [  8.919 s]
[INFO] Apache Kylin - Metrics Reporter Kafka .............. SUCCESS [  5.474 s]
[INFO] Apache Kylin - Stream Source Kafka ................. SUCCESS [  5.353 s]
[INFO] Apache Kylin - Stream Coordinator .................. SUCCESS [ 18.839 s]
[INFO] Apache Kylin - Stream Receiver ..................... SUCCESS [ 15.744 s]
[INFO] Apache Kylin - Stream Storage ...................... SUCCESS [  1.717 s]
[INFO] Apache Kylin - REST Server Base .................... SUCCESS [ 27.156 s]
[INFO] Apache Kylin - Tool ................................ SUCCESS [ 16.371 s]
[INFO] Apache Kylin - Cube Migration Service .............. SUCCESS [  2.950 s]
[INFO] Apache Kylin - REST Server ......................... SUCCESS [03:42 min]
[INFO] Apache Kylin - JDBC Driver ......................... SUCCESS [  8.377 s]
[INFO] Apache Kylin - Assembly ............................ SUCCESS [ 19.827 s]
[INFO] Apache Kylin - Tool Assembly ....................... SUCCESS [  4.140 s]
[INFO] Apache Kylin - Integration Test .................... SUCCESS [ 20.800 s]
[INFO] Apache Kylin - Tomcat Extension .................... SUCCESS [  1.077 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24:03 min
[INFO] Finished at: 2020-10-10T21:37:31+08:00
[INFO] ------------------------------------------------------------------------

**Comment by hit-lacus** [comment]
Thank you, that's great.

**Review by hit-lacus — APPROVED** [review]
Approved

**Pull request merged**
