### PR TITLE
add kylin properties for hadoop-azure

### PR DESCRIPTION
**Pull request by delulu**
here's the related doc: https://github.com/delulu/DeluWiki/blob/master/sharing/kylin.md

### CODE REVIEW

**Comment by delulu** [comment]
I've added some kylin properties to support hive sql and mapreduce job running on a remote HDInsight cluster.
@shaofengshi, @etherge pls help review it, thx.

**Comment by shaofengshi** [comment]
hi Delu, seems the changes are for constructing a hadoop "Configuration" object, no other extra change. If so, I guess configure these param/values in hdfs-site.xml or core-site.xml will take effective, as Kylin load the hadoop configurations from the host machine's classpath. Could you check that? 

We were able to run Kylin on AWS EMR with S3 as the hive source; That only need change the xml conf files, no Java code change. I think Azure is the similar.

**Comment by delulu** [comment]
@shaofengshi, yes, the changes are for hadoop configuration. If kylin runs on one hadoop-azure cluster, that is hive and mapreduce running on same cluster with hbase, there'll be no hadoop configuration change needed. 

But in my scenairo, kylin is deployed on Hbase cluster, while running hive sql/mapreduce job on a remote hadoop cluster. So I've added these property keys in kylin.property, then we can init a custom hadoop configuration object in runtime, and it'll have no influence on the underline DFS of Hbase.

My way to solve it is a bit tricky, it's great if there's a better way to solve it : )

And, I have to admit that this is not a general feature change, it's ok not to merge the changes into master, I can keep it in my private branch.

**Comment by shaofengshi** [comment]
Hi Delu,

I get it, thank you; 

Kylin already supports the read/write separated deployment: one cluster for Hive+Hadoop (write), the other (dedicated) cluster for HBase (read only); But the recommended deployment topologic is a little different with yours: it suggests running Kylin on a client machine whose HDFS/Hadoop/MR/Hive configurations point to the Hive cluster, but make the HBase configuration (hbase-site.xml) points to the HBase cluster. After that, in conf/kylin.properties, configure "kylin.hbase.cluster.fs" pointing to the NN of HBase; With this configuration, Kylin will automatically transfer the cube file to HBase cluster after building. 

This blog illustarte this: https://kylin.apache.org/blog/2016/06/10/standalone-hbase-cluster/

Suggest you have a check; if it can solve your issue without any code change, that would be great!

**Comment by delulu** [comment]
@shaofengshi, thx for your quick response : )

This is great! I get it and I'll try out this new deploy way.

You can close this pr now.

**Comment by handmail** [comment]
Hi all
I installed kylin 1.6, but the erros were following ：
Related cause: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'mvcContentNegotiationManager': Requested bean is currently in creation: Is there an unresolvable circular reference?

find-hbase.sh must be seted ?

Please help me. thak you!

**Comment by yiming187** [comment]
For questions, please use Kylin user mailer, user@kylin.apache.org. For more information, check out http://kylin.apache.org/community/

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
