### PR TITLE
KYLIN-3961 Optimize TopNCounter's merge function to reduce TopNCounter's error size.

### PR DESCRIPTION
**Pull request by zhaojintaozhao**
Sometimes TopN measure query will return a large error.
I optimize TopNCounter's merge function to reduce TopNCounter's errors when using TopN measure.
This optimization work well in my kylin system and reduce TopNCounter's error size.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by zhaojintaozhao** [comment]
> Hi jintao, I understand your change.
> 
> The current algorithm bases the algorithm of "a parallel space saving algorithm for frequent items and the Hurwitz zeta distribution", which you can find the link from the reference list of:
> 
> https://kylin.apache.org/blog/2016/03/19/approximate-topn-measure/
> 
> It will make the aggregated value bigger than the actual value, but it is to ensure the position be relatively close to actual.

Hi shaofeng:

I built 3 cubes and test the query performance and accuracy of TOPN.  
The first is normal cube without topN;  The second cube has topN measure with current version code. The third cube has topN measure with my modified code. Both  the topN measure of  the second and third cube is top100. The amount of source data is 22million, I build cube  30 days and using the same query sql. 
I find that both the second  and  third topN cube have a few errors to the actual. But  the second and third topN cube  is very fast than the first normal cube. The error of the  third cube is less than the second cube about position relatively to the actual. The aggregated value of the  second cube is larger than the actual, but the third cube doesn't have error about aggregated value.
Overall, the third modified cube is better than the second current code cube.

**Comment by nichunen** [comment]
Hi @zhaojintaozhao 

I agree that your pr will increase the accuracy of the counter number in some cases, but I'm afraid it will also break the results' oder. Look at the ut I've added in your pr.

The counter with item "DD" is supposed to be the top 1 after two times of merging, but with the code change, it will be  lost

**Comment by nichunen** [comment]
Close this pr for it violates the design of the topn algorithm.
@zhaojintaozhao Please reopen it if you can provide more convincing evidence

**Pull request closed without merging**
