### PR TITLE
3.1.0

### PR DESCRIPTION
**Pull request by ldy521314**
Can apache-kylin-3.1.0-bin-hbase1x be deployed in apache-hive-3.1.1-1.1.6-bin？ or Apache-kylin-3.1.0-bin-hbase1x supports apache-hive-3.1.1-1.1.6-bin？

### CODE REVIEW

**Comment by hit-lacus** [comment]
Please provided more detail, at least including:

```
hadoop version
hbase version
hive --version
```

**Comment by ldy521314** [comment]
hadoop-2.8.5-1.4.0
hbase-1.4.9-1.0.0
apache-hive-3.1.1-1.1.6-bin

xxyu <notifications@github.com> 于2020年8月6日周四 下午10:49写道：

**Comment by hit-lacus** [comment]
Please report a bug, please use [JIRA](https://issues.apache.org/jira/projects/KYLIN) and provided enough information.

**Comment by hit-lacus** [comment]
If you want to report a bug, please use [JIRA](https://issues.apache.org/jira/projects/KYLIN) and provided enough information.

**Pull request closed without merging**
