### PR TITLE
Update prepare-libs.sh

### PR DESCRIPTION
**Pull request by hyunseokJang**
add lib ( storage stream )

### CODE REVIEW

**Comment by hyunseokJang** [comment]
add.

**Comment by hit-lacus** [comment]
Hi, @hyunseokJang , if you don't mind, could please share with us why you add this line? 

I think that jar has been packaged in kylin binary.  Following is my findings.

image

**Comment by hyunseokJang** [comment]
oh, sorry. please this ignore this commit!.
It's my mistake.

**Comment by hit-lacus** [comment]
We are happy to see your next PR.  @hyunseokJang

**Pull request closed without merging**
