### PR TITLE
KYLIN-4185: optimize CuboidSizeMap by using historical segments

### PR DESCRIPTION
**Pull request by zhoukangcn**
see: https://issues.apache.org/jira/browse/kylin-4185

### CODE REVIEW

**Comment by zhoukangcn** [comment]
In our production envirement
```
# CASE 1: build segment 
cube size is 1706290.0134949684 before optimize
cube size is 156975.3352600266 after optimize
# dfs -du -s -h {path}/kylin-{uuid}/{cubeName}/cuboid
152.5 G 

# CASE 2: merge segment (another cube)
cube size is 10216.861420631409 before optimize
cube size is 15594.586000549038 after optimize
# dfs -du -s -h {path}/kylin-{uuid}/{cubeName}/cuboid
15.2 G
```

**Comment by zhoukangcn** [comment]
@nichunen Could you help to review this? Thank you

**Comment by nichunen** [comment]
@zhoukangcn Hi, would you please add another pr for the doc of this config?

**Comment by zhoukangcn** [comment]
@nichunen please see : https://github.com/apache/kylin/pull/1071

**Pull request merged**
