### PR TITLE
KYLIN-4050 Fix a CLI option parse error in FlinkMergingDictionary and some little code refactor

### PR DESCRIPTION
**Pull request by yanghua**
JIRA : https://issues.apache.org/jira/browse/KYLIN-4050

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by yanghua** [comment]
cc @nichunen

**Pull request merged**
