### PR TITLE
Add unit tests four

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added Unit Tests to improve code coverage.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by nichunen** [comment]
Hi @TheRealHaui   
It seems that you do not set "import order" in your IDE with file "core-common/.settings/org.eclipse.jdt.core.prefs", with this setting, java.* should be above of org.*

**Comment by TheRealHaui** [comment]
@nichunen,
I reordered the import statements like Eclipse does.

**Comment by TheRealHaui** [comment]
Obviously Travis has crashed or at least hangs.

**Comment by TheRealHaui** [comment]
@nichunen,
do you want to see further changes?

**Comment by nichunen** [comment]
@TheRealHaui  Hi, absolutely! Kylin's code coverage is growing with your contribution.

**Comment by TheRealHaui** [comment]
@nichunen,
ah, yes - thanks for your answer, looking forward to contribute more tests!
However, meant in my comment if you want to see further changes in this pull request prior to merging?

**Review by nichunen — APPROVED** [review]
Fine to me

**Comment by nichunen** [comment]
@TheRealHaui I've reviewed and merged. Thanks

**Comment by TheRealHaui** [comment]
@nichunen,
you are welcome!

**Pull request merged**
