### PR TITLE
KYLIN-3893: Cube build failed for wrong row key column description

### PR DESCRIPTION
**Pull request by lshmouse**
See: https://issues.apache.org/jira/browse/KYLIN-3893

We can catch the exception and make the exception the issue clear.

It's better to check this in the front end, but i  can not find how to fix it.  Anyone can give some advice? Thanks~

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
This is a kind of input validation, the best place is the first time when the cube is saved, in CubeController.saveCubeDesc(); Could you please to revise the modification? Thank you shaohui!

**Comment by lshmouse** [comment]
@shaofengshi Thanks for your advice. I will update the patch later.

**Comment by lshmouse** [comment]
Add row key column encoding validation when saving cube description

**Comment by nichunen** [comment]
Will be done in https://github.com/apache/kylin/pull/622, close this PR

**Pull request closed without merging**
