### PR TITLE
KYLIN-3898 Cube level properties are ineffective in the some build steps

### PR DESCRIPTION
**Pull request by TempleZhou**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hi Temple, I think the more clear way is in :

org.apache.kylin.job.JoinedFlatTable#generateCreateTableStatement(org.apache.kylin.metadata.model.IJoinedFlatTableDesc, java.lang.String)

Change ` String storageFormat = flatDesc.getDataModel().getConfig().getFlatTableStorageFormat();`

to 
` String storageFormat = flatDesc.getSegment().getConfig().getFlatTableStorageFormat();`

Which is to say, here using segment level config (which is also the cube level) is better than the model level config. Just let me know your idea.

**Comment by TempleZhou** [comment]
> Hi Temple, I think the more clear way is in :
> 
> org.apache.kylin.job.JoinedFlatTable#generateCreateTableStatement(org.apache.kylin.metadata.model.IJoinedFlatTableDesc, java.lang.String)
> 
> Change ` String storageFormat = flatDesc.getDataModel().getConfig().getFlatTableStorageFormat();`
> 
> to
> ` String storageFormat = flatDesc.getSegment().getConfig().getFlatTableStorageFormat();`
> 
> Which is to say, here using segment level config (which is also the cube level) is better than the model level config. Just let me know your idea.

Oh ~ you are right, changing the dataModel is a foolish way as there are different cube use same model.
I have tested the change you advised, no problem.

**Pull request merged**
