### PR TITLE
KYLIN-4864 Fix .travis.yml syntax

### PR DESCRIPTION
**Pull request by martin-g**
## Proposed changes

The commented line about `# mvn sonar:sonar -e -Dsonar.host.url=https://sonarcloud.io ...` has broken the YAML and because of this TravisCI didn't execute any jobs.
I wasn't able to find a way to preserve the commented line and fix the syntax, so I removed the line. Later it could be get from Git history to re-enable Sonar.

While here I've improved few more things:
- install OpenJDK and unzip for both AMD64 and ARM64. This way it uses latest JDK 8 (1.8.0_292) for both CPU architectures
- fix more YAML warnings

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [ x ] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I will prepare another pr against the `document` branch
- [ ] Any dependent changes have been merged

## Further comments

This PR fixes the setup of TravisCI.
But it seems there are failing tests from before which are not related to this PR.

### CODE REVIEW

**Comment by martin-g** [comment]
This PR is related to https://github.com/apache/kylin/pull/1558.
// CC @liusheng

**Comment by hit-lacus** [comment]
Thanks @martin-g !

**Comment by martin-g** [comment]
@hit-lacus Welcome!

Where could I find the source code of the website ? I'd like to fix https://kylin.apache.org/development/#ci-and-code-analysis. Currently it points to Jenkins, i.e. error 404.

**Comment by martin-g** [comment]
I think I've found it!
http://svn-master.apache.org/repos/asf/kylin/site/ - is this the one ?

**Comment by hit-lacus** [comment]
> I think I've found it!
> http://svn-master.apache.org/repos/asf/kylin/site/ - is this the one ?

The source code of apache kylin is located at https://github.com/apache/kylin . http://svn-master.apache.org/repos/asf/kylin/site/ is the official website .

**Comment by hit-lacus** [comment]
Following two files should be what you want : 
- https://github.com/apache/kylin/blob/document/website/_dev/index.md
- https://github.com/apache/kylin/blob/document/website/_dev/index.cn.md

**Comment by martin-g** [comment]
Docu update - https://github.com/apache/kylin/pull/1704

**Review by hit-lacus — APPROVED** [review]
LGTM

**Pull request merged**
