### PR TITLE
KYLIN-4172 Enable renaming column name for streaming table

### PR DESCRIPTION
**Pull request by nichunen**

### CODE REVIEW

**Comment by nichunen** [comment]
@hit-lacus Would you please review this PR?

**Comment by hit-lacus** [comment]
I have give it a test, so I apply your patch and build a new package, and deploy in my test env.

If we have the following sample message:

#### Sample
```json
{
    "act_type":"dislike",
    "event_ts_2":1574403423000,
    "pageview_id":"4dcc916f271e17",
    "event_ts":1574403423000,
    "play_duration":20.22,
    "multi_2":[
        "ele_1",
        "__%s",
        3
    ],
    "event_date_2":"2019-11-22 06:17:03",
    "video_type":"Sports",
    "play_times":16,
    "multi_1":{
        "key3":494593,
        "key2":17,
        "key1":{
            "key2":99
        }
    },
    "str_minute":"17",
    "str_minute_second":"6_17_3",
    "video_id":12,
    "event_date":"2019-11-22 06:17:03",
    "str_second":"3",
    "uid":7
}
```

#### Change the dimension name 
image

#### Change the dimension name  for derived time dimension
image

**Comment by hit-lacus** [comment]
### Table Info

image
image

### Cube Design
image

image


### Test Query
image

image

image

**Comment by hit-lacus** [comment]
I only find one issue, when you change name of time derived time dimension, you can not get right query result, you can try protect these column.

**Comment by nichunen** [comment]
@hit-lacus 
image
Rectified.

**Pull request merged**
