### PR TITLE
KYLIN-3801 Add --text flag in grep in find-hive-dependency.sh

### PR DESCRIPTION
**Pull request by kikniknik**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hello kikniknik, we're on holiday in this week, will check this in next week. Thank you!

**Comment by kikniknik** [comment]
In other grep uses input is clearly in text format, so there is no need to set "--text" flag in them.

**Pull request merged**
