### PR TITLE
KYLIN-4035 Calculate column cardinality by using spark engine

### PR DESCRIPTION
**Pull request by majic31**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by hit-lacus** [comment]
Cloud you please merge all these commit into one commit and force push? Thank you.

**Comment by majic31** [comment]
Ok, I will try it( I am sorry because I am not familiar with git operation ~ )

**Comment by majic31** [comment]
> Cloud you please merge all these commit into one commit and force push? Thank you.

Excuse me, How can I merge all commits into one commit?~ 
May I delete fork,  then re-fork, add my code and pr again? ~~

**Comment by hit-lacus** [comment]
@majic31  I think you should do the following:
1. reopen this PR
2. use `git log` and `git reset --soft ` to discard all commit from you, and use `git commit` to commit only one commit in local branch
3. use `git push -f origin ${YOUR_BRANCH_NAME}` to force push to remote branch


> If you want to discard all commit before commit xxx, please use `git reset --soft xxx`.
The following example discard three commit before b08935205a7aa1a00b6c09ef4625f45eacf9b013.

```sh
xiaoxiang.yu:SourceKylin/ (3997) $ git log -5 | cat                                                                                        [9:45:29]
commit 1f827d80de9685f067b54b6fb4ca129f94175f8d
Author: Liu Shaohui <liushaohui@xiaomi.com>
Date:   Sun Jun 9 16:47:58 2019 +0800

    KYLIN-3997: Add a health check job of Kylin

commit 670c2a98a82a699481eceddb685168104d5b185c
Author: chao long <wayne.l@qq.com>
Date:   Sun May 19 18:45:37 2019 +0800

    KYLIN-2620 TopN can't match when multi sort columns

commit 475df34fc27969414936e59a5ee2efd23cf2bcbe
Author: Na Zhai <38899902+GinaZhai@users.noreply.github.com>
Date:   Thu May 30 17:33:53 2019 +0800

    KYLIN-3893 Add validation for the encoding length and the type of encoding (#622)
    
    * KYLIN-3893 Add validation for the encoding length and the type of encoding
    * KYLIN-3893 Code review

commit b08935205a7aa1a00b6c09ef4625f45eacf9b013
Author: liapan <liapan@ebay.com>
Date:   Sun May 5 11:22:46 2019 +0800

    KYLIN-3980 Cube planner cuboid id error when dimensions too many

commit 47431ba0da7c3cce533f4d9dcd600654f33e0c90
Author: hit-lacus <hit_lacus@126.com>
Date:   Thu May 23 11:31:00 2019 +0800

    KYLIN-3958 Add quote for backtick
xiaoxiang.yu:SourceKylin/ (3997) $                                                                                                         [9:45:34]
xiaoxiang.yu:SourceKylin/ (3997) $ git reset --soft b08935205a7aa1a00b6c09ef4625f45eacf9b013                                               [9:45:36]

xiaoxiang.yu:SourceKylin/ (3997*) $ git log -5 | cat                                                                                       [9:46:02]
commit b08935205a7aa1a00b6c09ef4625f45eacf9b013
Author: liapan <liapan@ebay.com>
Date:   Sun May 5 11:22:46 2019 +0800

    KYLIN-3980 Cube planner cuboid id error when dimensions too many

commit 47431ba0da7c3cce533f4d9dcd600654f33e0c90
Author: hit-lacus <hit_lacus@126.com>
Date:   Thu May 23 11:31:00 2019 +0800

    KYLIN-3958 Add quote for backtick

commit f15b1f8a7ce05416dc1df2ee8a2ab629d1c00873
Author: javalife0312 <javalife0312@126.com>
Date:   Sun May 19 18:22:17 2019 +0800

    KYLIN-3958 MrHive-Dict support build by livy

commit 4e7b242b3009f1f194d2e66dae9b368330b89a7b
Author: shaofengshi <shaofengshi@apache.org>
Date:   Wed May 22 21:57:30 2019 +0800

    minor, switch to openjdk8 for travis

commit b48de90d046bfbef30917149e9c3426c6a7365cc
Author: Michael Hausegger <hausegger.michael@googlemail.com>
Date:   Tue May 21 04:18:57 2019 +0200

    Add unit tests (#645)
    
    * Add unit tests

```

If you have more question, please send me email to (xiaoxiang.yu@kyligence.io).

**Pull request closed without merging**
