### PR TITLE
KYLIN-4027, protect client execute

### PR DESCRIPTION
**Pull request by yuexingri**
rt

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Review by nichunen — APPROVED** [review]
Fine to me

**Pull request merged**
