### PR TITLE
KYLIN-4328 Add cache for succeed jobid in defaultFetcherRunner

### PR DESCRIPTION
**Pull request by ggKe**

### CODE REVIEW

**Comment by nichunen** [comment]
@ggKe Hi, thanks for the pr. I think PriorityFetcherRunner should also be modified.

**Comment by ggKe** [comment]
> @ggKe Hi, thanks for the pr. I think PriorityFetcherRunner should also be modified.
> @nichunen Hi,Thanks for your reply,I'm very pleasure to be able to do it.I will update as soon as possible and test the PriorityFetcherRunner.

**Comment by nichunen** [comment]
@ggKe Hi, please rebase your branch, here are 30 commits now.

**Comment by ggKe** [comment]
recommit PR to 1098 https://github.com/apache/kylin/pull/1098

**Pull request closed without merging**
