### PR TITLE
KYLIN-4365 fix RDBMS pushdown with clause bug

### PR DESCRIPTION
**Pull request by woyumen4597**

### CODE REVIEW

**Review by nichunen — APPROVED** [review]
LGTM

**Comment by zhangayqian** [comment]
### Check list
- [ ] Step 1. [**OPTIONAL**]Understand background/root cause/design basically(one hour EST) . Its issue type is 
    - [ ] bug fix
    - [x] new feature
    - [ ] enhancement
- [x] Step 2. Test cases are designed and documented (30 minutes EST).
- [x] Step 3. Prepare specific env, for example:
    - mock data (maybe some specific data type)
    - test env (maybe install a RDBMS instance).
- [x] Step 4. Verify and make sure test cases passed.
- [x] Step 5. Paste manual important steps and screenshots here (20 minutes EST). 
    - If you find difficulty in pick most important evidence, please attach diagnosis package. 
- [ ] Step 6. Do more check in user perspective (20 minutes EST)
    - [ ] Doc need be updated? And if it is updated? Ask help for release manager if so.
    - [ ] If it is a breaking change so we should notify Kylin community? Ask help for release manager if so.
- [x] Step 7.  Summarize this test (20 minutes EST).

### Total estimate
- 4 hours for small issue from optimistic estimate. 

### Note
If you find some unexpected and **unrelated** error/mistake, please DO report it if it is truly a mistake, I think we may research and fix it in the future.

If you find background information/root cause analysis is not complete or ambiguous, please try to contact to author or do a quick research and record what you find. It is a good chance to learn something interesting.

If you find it is not easy to design testcase, please notify release manager.

**Comment by zhangayqian** [comment]
## Design test case

### Test case
- Modify pushdown configuration in kylin.properties to pushdown query to SQLServer.
```
kylin.query.pushdown.runner-class-name=org.apache.kylin.query.adhoc.PushDownRunnerJdbcImpl
#
kylin.query.pushdown.update-enabled=false
kylin.query.pushdown.jdbc.url=jdbc:sqlserver://10.3.0.221:1433;databasename=temp
kylin.query.pushdown.jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
kylin.query.pushdown.jdbc.username=sa
kylin.query.pushdown.jdbc.password=
```
- Prepare `kylin_sales` table  in SQLserver
- Setup kylin and disable all cube in `learn_kylin`
- Execute sql
```
with tmp as (select buyer_id from kylin_sales),
tmp2 as (select * from kylin_sales) 
select * from tmp,tmp2 where tmp.buyer_id = tmp2.buyer_id
```
### Expected result
- SQL executed successfully and returned correct results.

**Comment by zhangayqian** [comment]
## Verify test case
image
image

**Pull request merged**
