### PR TITLE
KYLIN-3531 Save uppercase of usernames to metadata

### PR DESCRIPTION
**Pull request by ZhouYC627**
https://issues.apache.org/jira/browse/KYLIN-3531

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by ZhouYC627** [comment]
If login failed, try this command before kylin starts:
> $KYLIN_HOME/bin/metastore.sh remove /user

Restart Kylin. Now the usernames in metadata are all uppercase and kylin will ignore case in Web UI.

**Comment by Prashant01aug** [comment]
Facing issue while creating streaming table from Kylin 
Overwriting conflict /project/KYLIN_SYSTEM.json, expect old TS 1581041138000, but it is 1581041222000

**Pull request merged**
