### PR TITLE
Suggest changes for security concern

### PR DESCRIPTION
**Pull request by YYTVicky**

### CODE REVIEW

**Comment by shaofengshi** [comment]
Hello, would you please provide a description for this change? What's the impact if applying this change? Thanks!

**Comment by nichunen** [comment]
@YYTVicky Please create a Jira issue for your code change and resubmit a PR

**Comment by YYTVicky** [comment]
Hi,
   Thanks for your response, the vulnerability caused by the mode you chose, here is the document to refer (https://zachgrace.com/posts/attacking-ecb/), so when you use AES, our tool recommend ("AES/GCM", "AES/CFB", "AES/CBC", "AES/CTR/NoPadding","AES/CBC/PKCS5".
And sure, I will try to form a gira issue

Thanks

**Comment by Mahir92** [comment]
Hi @nichunen  , a [JIRA](https://issues.apache.org/jira/browse/KYLIN-4479) issue has been created and a [PR](https://github.com/apache/kylin/pull/1193) has been resubmitted as per your instruction to @YYTVicky  .

**Pull request closed without merging**
