### PR TITLE
Kylin es

### PR DESCRIPTION
**Pull request by zeliu**
add a new storage for elasticsearch.

### CODE REVIEW

**Comment by binmahone** [comment]
hi @zeliu  can you leave your email? want to engage you in dev list discussion on this PR

**Comment by zeliu** [comment]
hi @binmahone  ,I'm in the mailing list.  liuze8@wanda.cn.

**Comment by liyang-gmt8** [comment]
Do we have a JIRA on this great feature? En.. and this will be best to move to 2.x-staging branch

**Comment by jmozah** [comment]
is anyone working on this? i would like to help.

**Comment by lidongsjtu** [comment]
Please discuss this in mailing list or JIRA: https://issues.apache.org/jira/browse/KYLIN-1371

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
This PR is out of date. @zeliu is it possible to update it?

**Comment by shaofengshi** [comment]
This PR has been out of date. And it didn't introduce how it be designed, implemented and how to compare with other storage engine like HBase. Close it now.

**Pull request closed without merging**
