### PR TITLE
KYLIN-3874 "Convert Cuboid Data to HFile" failed when HBase and MR use different HDFS clusters

### PR DESCRIPTION
**Pull request by guangxuCheng**
Detail: https://issues.apache.org/jira/browse/KYLIN-3874

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Guangxu, thank you for the PR! We will review it soon.

**Comment by guangxuCheng** [comment]
Sorry, There is a small problem here. After modification, it may cause the configuration in "kylin_job_conf.xml" to be overwritten. Let me prepare a new patch, thanks!

**Comment by guangxuCheng** [comment]
Re-review the logic of this block, we only need to add the information about the nameservice of HBase's HDFS to the configuration. The patch has been updated.Thanks

**Pull request merged**
