### PR TITLE
KYLIN-4371 Integrate System Cube with Real-time OLAP

### PR DESCRIPTION
**Pull request by hit-lacus**
Issue https://issues.apache.org/jira/browse/KYLIN-4371

Some background at https://github.com/hit-lacus/hit-lacus.github.io/issues/86

### CODE REVIEW

**Comment by hit-lacus** [comment]
## Test

- sink.json
```json
[
  {
    "sink": "hive",
    "storage_type": 2,
    "cube_desc_override_properties": {
      "kylin.cube.algorithm": "INMEM",
      "kylin.cube.max-building-segments": "1"
    }
  },
  {
    "sink": "kafka",
    "storage_type": 3,
    "cube_desc_override_properties": {
      "kylin.cube.algorithm": "INMEM",
      "kylin.stream.cube.window": 28800,
      "kylin.stream.cube.duration": 3600,
      "kylin.stream.segment.retention.policy": "purge",
      "kylin.cube.max-building-segments": "20"
    },
    "table_properties": {
      "bootstrap.servers": "cdh-worker-1:9092,cdh-worker-2:9092,cdh-master:9092"
    }
  }
]
```


```sh
./bin/kylin.sh org.apache.kylin.tool.metrics.systemcube.SCCreator -inputConfig sink.json  -output system-cube
```

**Comment by kyotoYaho** [comment]
Great document. LGTM

**Comment by zhangayqian** [comment]
### Check list
- [ ] Step 1. [**OPTIONAL**]Understand background/root cause/design basically(one hour EST) . Its issue type is 
    - [ ] bug fix
    - [x] new feature
    - [ ] enhancement
- [x] Step 2. Test cases are designed and documented (30 minutes EST).
- [x] Step 3. Prepare specific env, for example:
    - mock data (maybe some specific data type)
    - test env (maybe install a RDBMS instance).
- [x] Step 4. Verify and make sure test cases passed.
- [x] Step 5. Paste manual important steps and screenshots here (20 minutes EST). 
    - If you find difficulty in pick most important evidence, please attach diagnosis package. 
- [x] Step 6. Do more check in user perspective (20 minutes EST)
    - [ ] Doc need be updated? And if it is updated? Ask help for release manager if so.
    - [ ] If it is a breaking change so we should notify Kylin community? Ask help for release manager if so.
- [ ] Step 7.  Summarize this test (20 minutes EST).

### Total estimate
- 4 hours for small issue from optimistic estimate. 

### Note
If you find some unexpected and **unrelated** error/mistake, please DO report it if it is truly a mistake, I think we may research and fix it in the future.

If you find background information/root cause analysis is not complete or ambiguous, please try to contact to author or do a quick research and record what you find. It is a good chance to learn something interesting.

If you find it is not easy to design testcase, please notify release manager.

**Comment by zhangayqian** [comment]
## Design test case

### Prepare test env 
- bin/kylin.sh start
- bin/kylin.sh streaming start

### Test case
- Create system cube with Real-time OLAP according to the document of this PR.
- Use system cube.

**Comment by zhangayqian** [comment]
## Verify test case
- System cube
image

- Dashboard
image
image

- Kylin log
image

**Comment by zhangayqian** [comment]
### Summary
- System cube with Real-time OLAP works well.

**Pull request merged**
