### PR TITLE
KYLIN-3749 add configuration to override xml for RDBMS

### PR DESCRIPTION
**Pull request by woyumen4597**

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by woyumen4597** [comment]
Local CI has passed.
image

**Comment by shaofengshi** [comment]
Hi Rongchuan, the change seems not to be related with KYLIN-3479, can you correct the JIRA ID?

**Comment by woyumen4597** [comment]
@shaofengshi  It's my mistake,I've corrected it.

**Pull request merged**
