### PR TITLE
KYLIN-3965 JDBC fix.

### PR DESCRIPTION
**Pull request by Sidonet**
- Driver manager compability.
- Add guava to uber-jar for standalone usage.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by Sidonet** [comment]
image

Tested on external project, with only kylin-jdbc.jar in dependicies

**Comment by nichunen** [comment]
retest

**Comment by nichunen** [comment]
retest this please

**Comment by adoroszlai** [comment]
retest

**Comment by Sidonet** [comment]
> retest this please

Hello, in my project i use build from this branch, due to DriverManager used in my project.
How will i need to retest it?

**Comment by nichunen** [comment]
> > retest this please
> 
> Hello, in my project i use build from this branch, due to DriverManager used in my project.
> How will i need to retest it?

Hello, I tried to re-trigger the jenkins build job by comment with "retest this plese"

**Comment by Sidonet** [comment]
Hello Ni Chunen,

Ok, i don't know about this feature.

I think that the rat plugin expect license on jdbc/src/main/resources/META-INF/services/java.sql.Driver file... There is no changes, what may affect it...

Is License needed in this file? On other apache project there is no license.
image

**Comment by nichunen** [comment]
Hi @Sidonet 

I think you should add this file to the apache-rat-plugin's exclude list on pom.xml

**Pull request merged**
