### PR TITLE
[KYLIN-4920]real-time stream support diff database hive table in lambda mode

### PR DESCRIPTION
**Pull request by liukun4515**
## Proposed changes

[KYLIN-4920](https://issues.apache.org/jira/browse/KYLIN-4920)

User can define stream lambda table in diff database.

If user just give the table name, the database of hive is default.
If user want to match the specified table which is not in the default database, user should give the database name.

image

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [ ] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If this change need a document change, I will prepare another pr against the `document` branch
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by liukun4515** [comment]
@hit-lacus  PTAL

**Comment by hit-lacus** [comment]
Could you please explain, in which way should user configure database of lambda cube use? In front-end page?

**Comment by liukun4515** [comment]
> Could you please explain, in which way should user configure database of lambda cube use? In front-end page?

Update the PR message.

If the database name in hive is `hive_database`, user should just add the prefix before the table name, just like `hive_database.your_table_name` .

**Review by hit-lacus — APPROVED** [review]
LGTM, thanks @liukun4515 !

**Pull request merged**
