### PR TITLE
KYLIN-3537

### PR DESCRIPTION
**Pull request by Sidonet**
Use Spark to build Cube on Yarn faild at Setp8 on HDP3.0
add HBase dependicies to avoid java.lang.NoClassDefFoundError

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Alexander, thanks for the PR! I think this is only for Hadoop 3/HBase 2 right? If so, the change should go to "master-hadoop3.1" branch. Just let me know so I can move the change to the right branch. Thank you!

**Comment by Sidonet** [comment]
Hello Shaofengshi!

Yes you are right, i've moved PR to correct branch.
Thanks!

**Comment by shaofengshi** [comment]
Hello, I have manually applied your PR to the master-hadoop3.1 and 2.6.x-hadoop3.1 branches so will close this PR. Thank for contributing to Kylin!

**Comment by shaofengshi** [comment]
Alexander, have you registered Apache JIRA? I want to add you to the Kylin team and then mark you as the assignee of KYLIN-3537.

**Comment by Sidonet** [comment]
Yes, i am.

alex.sidorchuk85

**Pull request closed without merging**
