### PR TITLE
[KYLIN-5159] upgrade some common libs due to CVEs

### PR DESCRIPTION
**Pull request by pjfanning**
## Proposed changes

Try to fix some old dependencies that have known security vulnerabilities

https://issues.apache.org/jira/browse/KYLIN-5159

## Types of changes

What types of changes does your code introduce to Kylin?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [X] I have create an issue on [Kylin's jira](https://issues.apache.org/jira/browse/KYLIN), and have described the bug/feature there in detail
- [X] Commit messages in my PR start with the related jira ID, like "KYLIN-0000 Make Kylin project open-source"
- [ ] Compiling and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged

## Further comments

If this is a relatively large or complex change, kick off the discussion at user@kylin or dev@kylin by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by pjfanning** [comment]
@hit-lacus @zhenfuxu would either of you be able to take a look at this?

**Comment by pjfanning** [comment]
@hit-lacus would you be able to review this?

**Comment by hit-lacus** [comment]
LGTM

**Comment by hit-lacus** [comment]
LGTM

**Pull request merged**
