### PR TITLE
Update BatchMergeJobBuilder2.java

### PR DESCRIPTION
**Pull request by yz490700477**
"Merge Cuboid Dictionary" step should load MapReduce config from kylin_job_conf.xml instead of kylin_job_conf_inmem.xml

### CODE REVIEW

**Comment by yz490700477** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ASF CI System"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月23日(星期一) 下午4:33
收件人:&nbsp;"apache/kylin"<kylin@noreply.github.com&gt;;
抄送:&nbsp;"詆調壹點"<490700477@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/kylin] Update BatchMergeJobBuilder2.java (#855)




Can one of the admins verify this patch?

**Comment by shaofengshi** [comment]
Hello, could you please describe your change? The merge dict step needs more memory than normal steps, that's why it uses the in-mem setting. Does that cause problem in your side? Thanks!

**Comment by nichunen** [comment]
@yz490700477 Hi, it's better to add a new job conf file for merging jobs

**Comment by nichunen** [comment]
Would you please update this PR?

**Pull request merged**
