### PR TITLE
KYLIN-3716 FastThreadLocal replaces ThreadLocal

### PR DESCRIPTION
**Pull request by SteNicholas**
In kylin query engine,QuerySevice acquires OLAPContext through ThreadLocal.In certain research,the development that FastThreadLocal replaces ThreadLocal to store thread OLAPContext is substantial performance improvement.

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by SteNicholas** [comment]
@shaofengshi I did maven test and rename the classes of threadlocal package that causes some exception you referred.I have already return to the origin class name and checked maven test passed.

**Comment by SteNicholas** [comment]
@shaofengshi Yeah,it is possible to add the dependency on netty and then use netty's "FastThreadLocal" class in Kylin.I simplify FastThreadLocal by using InternalThreadLocal and avoid more dependency in Kylin.Therefore, there is two ways to improve ThreadLocal performance by different aspects.

**Comment by shaofengshi** [comment]
Hi Nicholas, I merge the change by merging the two commits into one, and modified the commit message to follow Apache rule. Thanks for your patience!

**Pull request closed without merging**
