### PR TITLE
KYLIN-3913: Remove getAllOutputs api in ExecutableManager to avoid OOM for large metadata

### PR DESCRIPTION
**Pull request by lshmouse**
See: https://issues.apache.org/jira/browse/KYLIN-3913

### CODE REVIEW

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by nichunen** [comment]
Hi @lshmouse ,  have you tested your pr on a kylin instance with huge number of jobs. 

In your PR, org.apache.kylin.engine.mr.common.JobInfoConverter#parseToJobSearchResult will visit metastore to get the execute output data. I doubt this will decrease the performance, and make job listing slower.

**Comment by lshmouse** [comment]
@nichunen Thanks for your reviews. I will update performance data later.

**Comment by nichunen** [comment]
It will be done in https://github.com/apache/kylin/pull/630, the commit in this pr will be kept there, close this pr

**Pull request closed without merging**
